# Generated by Django 4.2 on 2026-06-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=100, verbose_name='Nama Program')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lokasi_logo/', verbose_name='Logo Program')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan',
                'verbose_name_plural': 'Pengaturan',
            },
        ),
    ]
