# Generated by Django 4.2 on 2026-06-18 04:51

from django.db import migrations, models
import django.db.models.deletion
import kesiswaan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiSiswa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jenis_mutasi', models.CharField(choices=[('Masuk', 'Masuk'), ('Keluar', 'Keluar')], max_length=10)),
                ('tanggal_mutasi', models.DateField()),
                ('alasan_mutasi', models.TextField()),
                ('sekolah_asal_tujuan', models.CharField(max_length=255)),
                ('no_surat_mutasi', models.CharField(max_length=100)),
                ('file_surat_mutasi', models.FileField(blank=True, null=True, upload_to=kesiswaan.models.get_surat_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutasi', to='siswa.siswa')),
            ],
            options={
                'db_table': 'mutasi_siswa',
            },
        ),
        migrations.CreateModel(
            name='BerkasSiswa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_berkas', models.CharField(max_length=50)),
                ('file_path', models.FileField(upload_to=kesiswaan.models.get_berkas_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berkas', to='siswa.siswa')),
            ],
            options={
                'db_table': 'berkas_siswa',
            },
        ),
        migrations.CreateModel(
            name='PenempatanKelas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keterangan', models.CharField(choices=[('Aktif', 'Aktif'), ('Naik Kelas', 'Naik Kelas'), ('Tinggal Kelas', 'Tinggal Kelas')], default='Aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kelas', to='siswa.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.tahunajaran')),
            ],
            options={
                'db_table': 'penempatan_kelas',
                'unique_together': {('siswa', 'tahun_ajaran')},
            },
        ),
    ]
