# Generated by Django 4.2 on 2026-06-18 04:51

from django.db import migrations, models
import django.db.models.deletion
import siswa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nisn', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nik', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(blank=True, max_length=30)),
                ('golongan_darah', models.CharField(blank=True, max_length=3)),
                ('catatan_medis', models.TextField(blank=True)),
                ('alamat_tinggal', models.TextField()),
                ('status_siswa', models.CharField(choices=[('Aktif', 'Aktif'), ('Lulus', 'Lulus'), ('Mutasi Keluar', 'Mutasi Keluar'), ('Drop Out', 'Drop Out')], default='Aktif', max_length=20)),
                ('tanggal_masuk', models.DateField(help_text='Tanggal resmi diterima')),
                ('tanggal_keluar', models.DateField(blank=True, null=True)),
                ('foto_masuk', models.ImageField(blank=True, null=True, upload_to=siswa.models.get_upload_path)),
                ('foto_keluar', models.ImageField(blank=True, null=True, upload_to=siswa.models.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='DataOrangTua',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_ayah', models.CharField(blank=True, max_length=255)),
                ('pekerjaan_ayah', models.CharField(blank=True, max_length=100)),
                ('no_hp_ayah', models.CharField(blank=True, max_length=20)),
                ('nama_ibu', models.CharField(blank=True, max_length=255)),
                ('pekerjaan_ibu', models.CharField(blank=True, max_length=100)),
                ('no_hp_ibu', models.CharField(blank=True, max_length=20)),
                ('nama_wali', models.CharField(blank=True, max_length=255)),
                ('pekerjaan_wali', models.CharField(blank=True, max_length=100)),
                ('no_hp_wali', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orang_tua', to='siswa.siswa')),
            ],
            options={
                'db_table': 'data_orang_tua',
            },
        ),
    ]
