# Generated by Django 4.2 on 2026-06-19 01:35

from django.db import migrations, models
import django.db.models.deletion
import siswa.models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='foto_keluar',
            field=models.ImageField(blank=True, null=True, upload_to=siswa.models.get_foto_path),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto_masuk',
            field=models.ImageField(blank=True, null=True, upload_to=siswa.models.get_foto_path),
        ),
        migrations.CreateModel(
            name='LogRiwayat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aksi', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_riwayat', to='siswa.siswa')),
            ],
            options={
                'db_table': 'log_riwayat_siswa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DokumenSiswa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jenis_dokumen', models.CharField(choices=[('akte_kelahiran', 'Akte Kelahiran'), ('kartu_keluarga', 'Kartu Keluarga'), ('ijazah', 'Ijazah'), ('transkip_nilai', 'Transkip Nilai'), ('ktp', 'KTP'), ('lainnya', 'Lainnya')], max_length=30)),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('file_dokumen', models.FileField(upload_to=siswa.models.get_upload_path)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='siswa.siswa')),
            ],
            options={
                'db_table': 'dokumen_siswa',
            },
        ),
    ]
