# Generated by Django 4.2 on 2026-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_alter_siswa_foto_keluar_alter_siswa_foto_masuk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='agama',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Khonghucu', 'Khonghucu')], max_length=30),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='golongan_darah',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3),
        ),
    ]
