# Generated by Django 4.2 on 2026-06-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_jurusan', models.CharField(max_length=100)),
                ('kode_jurusan', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jurusan',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tahun', models.CharField(help_text='Contoh: 2025/2026', max_length=9)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('is_aktif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tahun_ajaran',
                'unique_together': {('tahun', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=50)),
                ('tingkat', models.IntegerField(help_text='10, 11, atau 12')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.jurusan')),
            ],
            options={
                'db_table': 'kelas',
            },
        ),
    ]
